// src/components/Footer.tsx
// src/components/Footer.tsx
import { useState, useEffect } from "react";
import { animateScroll as scroll } from "react-scroll";
import styles from "../styles/components/Footer.module.css";
import { FaGithub, FaLinkedin, FaEnvelope } from "react-icons/fa";
import BlueSkyLogo from "../assets/logo/Bluesky_Logo.svg"; // Import the logo

function Footer() {
  const [isVisible, setIsVisible] = useState(false);
  const currentYear = new Date().getFullYear();

  // Show button when page is scrolled down
  const toggleVisibility = () => {
    if (window.scrollY > 300) {
      setIsVisible(true);
    } else {
      setIsVisible(false);
    }
  };

  // Set up scroll event listener
  useEffect(() => {
    window.addEventListener("scroll", toggleVisibility);
    return () => window.removeEventListener("scroll", toggleVisibility);
  }, []);

  // Scroll to top function using react-scroll
  const scrollToTop = () => {
    scroll.scrollToTop({
      duration: 800,
      smooth: "easeInOutQuart",
    });
  };

  return (
    <footer className={styles.footer}>
      <div className={styles.footerContent}>
        <div className={styles.socialLinks}>
          <a
            href="https://bsky.app/profile/gnoblet.bsky.social"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="Bluesky"
            className={styles.blueskyLink}
          >
            <img
              src={BlueSkyLogo}
              alt="Bluesky"
              className={styles.blueskyIcon}
            />
          </a>
          <a
            href="https://github.com/gnoblet"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="GitHub"
          >
            <FaGithub />
          </a>
          <a
            href="https://www.linkedin.com/in/gnoblet/"
            target="_blank"
            rel="noopener noreferrer"
            aria-label="LinkedIn"
          >
            <FaLinkedin />
          </a>
          <a href="mailto:gnoblet@zaclys.net" aria-label="Email">
            <FaEnvelope />
          </a>
        </div>

        <p className={styles.copyright}>
          &copy; {currentYear} Guillaume Noblet
        </p>

        {/* Scroll to Top Button */}
        <button
          onClick={scrollToTop}
          className={`${styles.scrollTopButton} ${isVisible ? styles.visible : ""}`}
          aria-label="Scroll to top"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            width="24"
            height="24"
            viewBox="0 0 24 24"
            fill="none"
            stroke="currentColor"
            strokeWidth="2"
            strokeLinecap="round"
            strokeLinejoin="round"
          >
            <path d="M12 19V5M5 12l7-7 7 7" />
          </svg>
        </button>
      </div>
    </footer>
  );
}

export default Footer;

// src/lib/components/Footer.svelte
<script lang="ts">
    import { onMount, onDestroy } from "svelte";
    import { browser } from "$app/environment";

    let isVisible = false;
    const currentYear = new Date().getFullYear();

    function toggleVisibility() {
        if (browser && window.scrollY > 300) {
            isVisible = true;
        } else {
            isVisible = false;
        }
    }

    function scrollToTop() {
        if (browser) {
            window.scrollTo({
                top: 0,
                behavior: "smooth",
            });
        }
    }

    onMount(() => {
        if (browser) {
            window.addEventListener("scroll", toggleVisibility);
        }
    });

    onDestroy(() => {
        if (browser) {
            window.removeEventListener("scroll", toggleVisibility);
        }
    });
</script>

<footer class="footer footer-center bg-base-200 text-base-content p-10">
    <aside class="max-w-sm">
        <p class="font-bold text-xl">
            Guillaume Noblet &copy; {currentYear}
        </p>
        <p class="text-sm opacity-80 mt-2">
            Thanks to <a
                href="https://a2-ai.github.io/rv-docs/"
                class="link link-hover"
                target="_blank"
                rel="noopener noreferrer">rv</a
            >
            and
            <a
                href="https://rspatial.org/pkg/"
                class="link link-hover"
                target="_blank"
                rel="noopener noreferrer">terra</a
            >
            for elevation data with R • contributors to Svelte, daisyUI, d3.js, splide.js,
            and Tailwind CSS.
        </p>
    </aside>
    <nav>
        <div class="grid grid-flow-col gap-4">
            <a
                href="https://github.com/gnoblet"
                class="btn btn-ghost btn-square btn-lg"
                aria-label="GitHub"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 24 24"
                    class="fill-current"
                >
                    <path
                        d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"
                    ></path>
                </svg>
            </a>
            <a
                href="https://www.linkedin.com/in/gnoblet/"
                class="btn btn-ghost btn-square btn-lg"
                aria-label="LinkedIn"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 24 24"
                    class="fill-current"
                >
                    <path
                        d="M20.447 20.452h-3.554v-5.569c0-1.328-.027-3.037-1.852-3.037-1.853 0-2.136 1.445-2.136 2.939v5.667H9.351V9h3.414v1.561h.046c.477-.9 1.637-1.85 3.37-1.85 3.601 0 4.267 2.37 4.267 5.455v6.286zM5.337 7.433c-1.144 0-2.063-.926-2.063-2.065 0-1.138.92-2.063 2.063-2.063 1.14 0 2.064.925 2.064 2.063 0 1.139-.925 2.065-2.064 2.065zm1.782 13.019H3.555V9h3.564v11.452zM22.225 0H1.771C.792 0 0 .774 0 1.729v20.542C0 23.227.792 24 1.771 24h20.451C23.2 24 24 23.227 24 22.271V1.729C24 .774 23.2 0 22.222 0h.003z"
                    ></path>
                </svg>
            </a>
            <a
                href="https://bsky.app/profile/gnoblet.bsky.social"
                class="btn btn-ghost btn-square btn-lg"
                aria-label="Bluesky"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 24 24"
                    class="fill-current"
                >
                    <path
                        d="M12 10.8c-1.087-2.114-4.046-6.053-6.798-7.995C2.566.944 1.561 1.266.902 1.565.139 1.908 0 3.08 0 3.768c0 .69.378 5.65.624 6.479.815 2.736 3.713 3.66 6.383 3.364.136-.02.275-.039.415-.056-.138.022-.276.04-.415.056-3.912.58-7.387 2.005-2.83 7.078 5.013 5.19 6.87-1.113 7.823-4.308.953 3.195 2.05 9.271 7.733 4.308 4.267-4.308 1.172-6.498-2.74-7.078a8.741 8.741 0 0 1-.415-.056c.14.017.279.036.415.056 2.67.297 5.568-.628 6.383-3.364.246-.828.624-5.79.624-6.478 0-.69-.139-1.861-.902-2.206-.659-.298-1.664-.62-4.3 1.24C16.046 4.748 13.087 8.687 12 10.8z"
                    ></path>
                </svg>
            </a>
            <a
                href="mailto:data@guillaume-noblet.com"
                class="btn btn-ghost btn-square btn-lg"
                aria-label="Email"
            >
                <svg
                    xmlns="http://www.w3.org/2000/svg"
                    width="32"
                    height="32"
                    viewBox="0 0 24 24"
                    class="fill-current"
                >
                    <path
                        d="M20 4H4c-1.1 0-1.99.9-1.99 2L2 18c0 1.1.9 2 2 2h16c1.1 0 2-.9 2-2V6c0-1.1-.9-2-2-2zm0 4l-8 5-8-5V6l8 5 8-5v2z"
                    ></path>
                </svg>
            </a>
        </div>
    </nav>
</footer>

<!-- Scroll to Top Button with Heroicon -->
{#if isVisible}
    <button
        on:click={scrollToTop}
        class="btn btn-square btn-primary fixed bottom-8 right-8 z-50 transition-all duration-300 hover:scale-110"
        aria-label="Scroll to top"
    >
        <!-- Heroicon: arrow-up -->
        <svg
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            stroke-width="2"
            stroke="currentColor"
            class="w-6 h-6"
        >
            <path
                stroke-linecap="round"
                stroke-linejoin="round"
                d="M4.5 10.5 12 3m0 0 7.5 7.5M12 3v18"
            />
        </svg>
    </button>
{/if}
